definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  models.Student:
    properties:
      cpf:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      rg:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /students:
    get:
      consumes:
      - application/json
      description: Find Student Created
      parameters:
      - description: student search by cpf
        format: email
        in: query
        name: cpf
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Find Student By CPF values
      tags:
      - Add-swagger-by-jcqueiroz
    post:
      consumes:
      - application/json
      description: Create New Student
      parameters:
      - description: Models of student
        in: body
        name: students
        required: true
        schema:
          $ref: '#/definitions/models.Student'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Create new Student values
      tags:
      - Add-swagger-by-jcqueiroz
  /students/:id:
    patch:
      consumes:
      - application/json
      description: Edit by json Student
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      - description: Edit Student
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/models.Student'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Edit an Student
      tags:
      - Add-swagger-by-jcqueiroz
  /students/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Student Created
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Delete Student values
      tags:
      - Add-swagger-by-jcqueiroz
    get:
      consumes:
      - application/json
      description: Find Student Created
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Find Student By ID values
      tags:
      - Add-swagger-by-jcqueiroz
swagger: "2.0"
